- name: Deploy Ubuntu VM on Proxmox
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create VM
      community.general.proxmox_kvm:
        api_host: "192.168.30.155"
        api_user: "terraform@pve"
        api_password: "b7fc6575-d485-4b12-bec3-c82c3f7c64cd"
        node: "pve"
        name: "ubuntu-vm"
        vmid: 1010
        memory: 2048
        cores: 2
        sockets: 1
        scsi:
          - scsi0: "local-lvm:20G"  # Corrected to pass a dictionary
        ostype: "l26"
        boot: "c"
        state: "present"
